name: Python CI com Testes 

on: 
  push:
    branches: [ main ] 
  pull_request:
    branches: [ main ]

jobs:
  build-and-test: 
    runs-on: ubuntu-latest 

    steps:
      - name: 1. Checkout do Repositório
        uses: actions/checkout@v4 

      - name: 2. Configurar Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.10' 

      - name: 3. Instalar Dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 4. Executar Testes com Pytest
        run: pytest

      - name: 5. Exibir versão do Python (Opcional)
        run: python --version
